packages:
  - '.' # the root 'package.json'
  - 'webook' # 'webook/package.json'
  - 'weboratory/**' # 'any package.json under weboratory/'
  - 'webrary/**' # 'any package.json under webrary/'
# @see https://pnpm.io/zh/pnpm-workspace_yaml